version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - app-network
    environment:
      - PHP_IDE_CONFIG=serverName=${APP_NAME}

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./app:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
